### ISSUE TITLE
Embed Obsidian Note as Frame?

### ISSUE THREAD

**Issue by j-finger** [Ellpeck/ObsidianCustomFrames#126]
I have a heatmap calendar plugin that I use and I want to embed the file as a frame. At the moment I am just placing the note in my sidebar but it's not as clean as I would like. Is this possible? I've tried point the URL to the file but it's not rendering anything

Desired Functionality
![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/80647966/86b83740-1be5-41c0-b2b5-72ca66016268)

**Comment by j-finger** [comment]
Never mind. I figured it out with custom css. I added the property `"cssclass" = .heatmap`  to the YAML of my heatmap file. Then I used the following CSS snippet to clean it up a little (centring, removal of title & turn off scrolling)

```css
/* targets the .heatmap css class, centres the content and turns off scrolling */
.heatmap {
    display: stretch;
    height: 100%;
    width: 100%;
    overflow-y: hidden;
    padding-top: 0px;
    margin-top: -20px;
}

/* removes the title. May not be necessary  */
.heatmap .view-header-title{
    display: none
  }

/* removes the title. 100% necessary */
.heatmap .inline-title{
    display: none;
  }
```

Still it would be nice to have this as a pane/frame with an icon instead of a note
