### ISSUE TITLE
[Feature Request] Allow Zoom in and out options for all iframes within settings. 

### ISSUE THREAD

**Issue by Obadiahcruz** [Ellpeck/ObsidianCustomFrames#13]
i currently use 
```css
html {
-webkit-transform: scale(0.85);
}
````
to zoom out for wikipedia mobile view frame in obsidian desktop 

im hoping for an option to probably cmd+scroll with mouse wheel like plugins do for images 
and/or 
have a setting option for zooming out within the settings
