### ISSUE TITLE
How to make custom frames switch Light mode or Dark mode automatically?

### ISSUE THREAD

**Issue by FeiLZX3Km** [Ellpeck/ObsidianCustomFrames#68]
How to make custom frames switch Light mode or Dark mode automatically?

**Comment by Victor1266** [comment]
+1. Also looking for this feature to be implemented

**Comment by BrightStar219** [comment]
+1 too.

Google Calendar: Replaced the original CSS with this one (stupid hack), and managed to get it in dark mode.
 html {
        -webkit-filter: invert(90%) hue-rotate(180deg)!important;
        filter: invert(90%) hue-rotate(180deg)!important;
        background: rgb(25, 25, 25)!important;
    }

**Comment by joshuadanpeterson** [comment]
Nice! @BrightStar219 I modified it into a slightly more refined version that also keeps the images and videos in their original colors:

```css
/* Apply the dark filter and background to the HTML and specific divs, set text to white */
html, .view-content.custom-frames-view, .workspace-leaf.mod-active {
  -webkit-filter: invert(90%) hue-rotate(180deg) !important;
  filter: invert(90%) hue-rotate(180deg) !important;
  background: rgb(25, 25, 25) !important;
  color: var(--text-white) !important;
}

/* Reset filters for images and other elements you don't want to be affected */
img, video {
  -webkit-filter: invert(100%) hue-rotate(-180deg) !important;
  filter: invert(100%) hue-rotate(-180deg) !important;
}
```

This should give you the dark mode feel without messing up your images or videos. Cheers! 🌙
